AddEventHandler('version_control:register', function(resource_name, repository, current_version, cb)
  local vc = Version(resource_name, repository, current_version)
  table.insert( CVersions, vc )
  cb(CVersions[#CVersions])
end)